# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ijepa-try',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/ijepa-try',
                'lib_path': 'ijepa_try'},
  'syms': {'ijepa_try.core': {'ijepa_try.core.foo': ('core.html#foo', 'ijepa_try/core.py')}}}
